### ISSUE TITLE
Include rootValue in mutations?

### ISSUE THREAD

**Issue by YourDeveloperFriend** [graphql/graphql-relay-js#15]
I'm trying to implement a login mutation, which would mutate the user's session. I used the example shown on [express-graphql|https://github.com/graphql/express-graphql#advanced-options] to add the session to the rootValue, but now I can't access that session in `mutateAndGetPayload`. I recommend adding rootValue to the `mutateAndGetPayload` call: necessary changes [here|https://github.com/graphql/graphql-relay-js/blob/master/src/mutation/mutation.js#L85].

**Comment by dschafer** [comment]
Just commented on the PR; the second argument to `mutateAndGetPayload` is a `GraphQLResolveInfo`, which should contain the `rootValue` in it.

Let me know if this solves the issue!

**Comment by dschafer** [comment]
Looks like this was resolved in the discussion on #16.

**Comment by spyalert01** [comment]
@YourDeveloperFriend 
I still don't understand How you get it solved?
I am trying to get the session value as well. and I also followed this :  [express-graphql|https://github.com/graphql/express-graphql#advanced-options] 

when my page is loaded, not even doing any mutation, from GraphQL I want to be able to access the value in my session, and from the session value, I want to do something.

How should I do it?

I tried this:

var queryType = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    node: nodeField,
    // Add your own root fields here
    viewer: {
      type: userType,
      resolve: ({rootValue}) => {
				return getViewer();
			},
    },
  }),
});

When the page is loaded, it says rootValue is undefined

**Comment by YourDeveloperFriend** [comment]
```javascript
// It's possible your issue is this line:
// resolve: ({rootValue}) => {
// Try removing the brackets:
resolve: (rootValue) => {
  console.log(rootValue);
  console.log(arguments);
}
```

**Comment by spyalert01** [comment]
Hi I have got it done
it should be resolve(parentValue, _, {rootValue:{session}})

Thanks.

**Comment by CoericK** [comment]
Hey @YourDeveloperFriend  im trying to implement a login to, and i want to create the cooki inside the `mutateAndGetPayload ` its that possible? so i can set res.cookie('token', 'mytokencreated'); @josephsavona any idea?

**Comment by prijindal** [comment]
The second argument does not seem to have a rootValue

**Comment by nikitindiz** [comment]
@prijindal the third one has, the second one is seems to be the `request` object.
